---
#========================================================================
# Copyright Universidade Federal do Espirito Santo (Ufes)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# 
# This program is released under license GNU GPL v3+ license.
#
#========================================================================

services:

    # web app
    boca-web:
        image: ghcr.io/joaofazolo/boca-docker/boca-web:latest
        depends_on:
            - boca-db
        environment:
            # database configuration
            # privileged user password
            - BOCA_DB_SUPER_PASSWORD=superpass
            # - BOCA_FORGOT_PASSWORD_LINK=https://senha.inf.ufes.br/
        volumes:
            - ./src/admin/site.php:/var/www/boca/src/admin/site.php
            - ./src/admin/user.php:/var/www/boca/src/admin/user.php
            - ./src/optionlower.php:/var/www/boca/src/optionlower.php
            - ./src/team/files.php:/var/www/boca/src/team/files.php
        ports: 
            - 8000:80

    # online judge
    boca-jail:
        image: ghcr.io/joaofazolo/boca-docker/boca-jail:latest
        privileged: true
        depends_on:
            - boca-db

    # database
    boca-db:
        image: postgres:14-alpine
        environment:
            # database configuration
            # privileged user password
            - POSTGRES_PASSWORD=superpass
